pipeline {
    agent any

    environment {
        MAVEN_HOME = tool name: 'maven-3.9'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm // Use 'checkout scm' to checkout code from Git
            }
        }

        stage('Build') {
            steps {
                script {
                    // Ensure the 'mvn' command is available in the PATH
                    def mvnHome = tool 'maven-3.9'
                    env.PATH = "/opt/maven-3.9/bin:${env.PATH}"
                }
                sh 'mvn clean package'
            }
        }
    }
}
